<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistSassLintLinter' => 'lint/linter/ArcanistSassLintLinter.php',
    'ArcanistScssLintLinter' => 'lint/linter/ArcanistScssLintLinter.php',
    'DockerizedPytestTestEngine' => 'unit/engine/DockerizedPytestTestEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistSassLintLinter' => 'ArcanistExternalLinter',
    'ArcanistScssLintLinter' => 'ArcanistExternalLinter',
    'DockerizedPytestTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
